apps/urls.py
from django.contrib import admin
from django.urls import path, include

import theme.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', theme.views.home, name='home'),
    path('customers/', include('customers.urls')),

]

customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'

urlpatterns = [
    path('', views.home, name='home'),

    path('customer_view/<int:pk>/', views.customer_view, name='customer_view'),
    path('customer_new', views.customer_create, name='customer_new'),
    path('customer_edit/<int:pk>/', views.customer_update, name='customer_edit'),
    path('customer_delete/<int:pk>/', views.customer_delete, name='customer_delete'),

    path('address_new/<int:parent_pk>/', views.address_create, name='address_new'),
    path('address_edit/<int:pk>/', views.address_update, name='address_edit'),
    path('address_delete/<int:pk>/', views.address_delete, name='address_delete'),
]

customers/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()

    def __str__(self):
        return self.name


class Address(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    city = models.CharField(max_length=200)
    country = models.TextField()

    def __str__(self):
        return "Address from: " + self.city

theme/models.py
from django.db import models

# Create your models here.

customers/forms.py
from django.forms import ModelForm

from .models import Customer, Address

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'age']

class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = ['city', 'country']

customers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from .models import Customer, Address
from .forms import CustomerForm, AddressForm


# ========== Home =========

def home(request, template_name='customers/home.html'):
    customers = Customer.objects.all()
    ctx = {
        'customers': customers,
    }
    return render(request, template_name, ctx)
    

# ========== customers CRUD =========

def customer_view(request, pk, template_name='customers/customer_view.html'):
    customer= get_object_or_404(Customer, pk=pk)
    addresses = Address.objects.filter(customer=customer)
    ctx = {
        'customer': customer,
        'addresses': addresses,
    }
    return render(request, template_name, ctx)

def customer_create(request, template_name='customers/customer_form.html'):
    form = CustomerForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('customers:home')
    ctx = {
        'form': form,
    }
    return render(request, template_name, ctx)

def customer_update(request, pk, template_name='customers/customer_form.html'):
    customer= get_object_or_404(Customer, pk=pk)
    form = CustomerForm(request.POST or None, instance=customer)
    if form.is_valid():
        form.save()
        return redirect('customers:home')
    ctx = {
        'form': form,
        'customer': customer,
    }
    return render(request, template_name, ctx)

def customer_delete(request, pk, template_name='customers/customer_confirm_delete.html'):
    customer= get_object_or_404(Customer, pk=pk)    
    if request.method=='POST':
        customer.delete()
        return redirect('customers:home')
    ctx = {
        'object': customer,
        'customer': customer,
    }
    return render(request, template_name, ctx)


# ========== Address CRUD =========

def address_create(request, parent_pk, template_name='customers/address_form.html'):
    customer = get_object_or_404(Customer, pk=parent_pk)
    form = AddressForm(request.POST or None)
    if form.is_valid():
        address = form.save(commit=False)
        address.customer = customer
        address.save()
        return redirect('customers:customer_view', parent_pk)
    ctx = {
        'form': form,
        'customer': customer,
    }
    return render(request, template_name, ctx)

def address_update(request, pk, template_name='customers/address_form.html'):
    address = get_object_or_404(Address, pk=pk)
    parent_pk = address.customer.pk
    form = AddressForm(request.POST or None, instance=address)
    if form.is_valid():
        form.save()
        return redirect('customers:customer_view', parent_pk)
    ctx = {
        'form': form,
        'customer': address.customer,
    }
    return render(request, template_name, ctx)

def address_delete(request, pk, template_name='customers/address_confirm_delete.html'):
    address = get_object_or_404(Address, pk=pk)    
    parent_pk = address.customer.pk
    if request.method=='POST':
        address.delete()
        return redirect('customers:customer_view', parent_pk)
    ctx = {
        'object': address,
        'customer': address.customer,
    }
    return render(request, template_name, ctx)

theme/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

customers/templates/customers/address_confirm_delete.html
{% extends "base.html" %}


{% block content %}
{% include "customers/nav.html" with customer=customer title="Delete Address" %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

customers/templates/customers/address_form.html
{% extends "base.html" %}


{% block content %}
{% include "customers/nav.html" with customer=customer title="Edit Address" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

customers/templates/customers/customer_confirm_delete.html
{% extends "base.html" %}

{% block content %}
{% include "customers/nav.html" with customer=customer title="Delete" %}

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

customers/templates/customers/customer_form.html
{% extends "base.html" %}


{% block content %}
{% include "customers/nav.html" with customer=customer title="Edit" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

customers/templates/customers/customer_view.html
{% extends "base.html" %}


{% block content %}
{% include "customers/nav.html" with customer=customer title="View" %}

Age: {{ customer.age }}

<h2>Addresses</h2>
<ul>
    {% for address in addresses %}
    <li>
        {{ address.city }}<br>
        {{ address.country|linebreaks }}
        <br>
        <a href="{% url 'customers:address_edit' address.id %}">edit</a>
        <a href="{% url 'customers:address_delete' address.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'customers:address_new' customer.id %}">New Address</a>
{% endblock %}

customers/templates/customers/home.html
{% extends "base.html" %}

{% block title %}Customer List{% endblock %}

{% block content %}
{% include "customers/nav.html" %}

Customers Parent/Child with Multi View

<ul>
    {% for customer in customers %}
    <li>{{ customer.name }}  ({{ customer.age }} Age )
    <a href="{% url 'customers:customer_view' customer.id %}">view</a>
    <a href="{% url 'customers:customer_edit' customer.id %}">edit</a>
    <a href="{% url 'customers:customer_delete' customer.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'customers:customer_new' %}">New</a>
{% endblock %}

customers/templates/customers/nav.html
<h2>
<a href="{% url 'customers:home' %}">Application Home</a>
{% if customer %}
&gt; <a href="{% url 'customers:customer_view' customer.id %}">{{ customer.name }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

theme/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django CRUD: {% block title %}Welcome{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" media="all" rel="stylesheet" />
</head>

<body>
<div id="wrapper">
    <h1><a href="{% url 'home' %}">Django CRUD Parent/Child Edition</a></h1>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div><!-- wrapper -->
</body>
</html>

theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<ul>

<li><a href="{% url 'customers:home' %}">Parent/Child using multiple views</a></li>
</ul>

You can also access Django built-in <a href="/admin/">Admin interface</a>, you would need to
create a user using the following command:

<pre>./manage.py  createsuperuser</pre>
{% endblock %}